import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#131016',
    padding: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  projectName: {
    color: '#31CF67',
    fontSize: 36,
    fontWeight: 'bold',
    marginBottom: 16,
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  title: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '600',
    marginBottom: 32,
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#1F1E25',
    borderRadius: 8,
    color: '#FFFF',
    padding: 16,
    fontSize: 16,
    flex: 1,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#31CF67',
  },
  button: {
    width: 120,
    height: 50,
    borderRadius: 8,
    backgroundColor: '#31CF67',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  form: {
    width: '100%',
    flexDirection: 'row',
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
